export default {
    screen_logo: require('../assets/images/screen_logo.png'),
    check: require('../assets/images/check.png'),
    unchecked: require('../assets/images/unchecked.png'),
    Loadingimg: require('../assets/images/Loadingimg.gif'),
    CheckCircle: require('../assets/images/CheckCircle.png'),
    backPage: require('../assets/images/backPage.png'),
    circle: require('../assets/images/circle.png'),
    sucesspayment: require('../assets/images/sucesspayment.png'),
    Getinfo: require('../assets/images/Getinfo.png'),
    star: require('../assets/images/star.png'),
    Close: require('../assets/images/close.png'),
    banner1: require('../assets/images/banner1.png'),
    banner2: require('../assets/images/banner2.png'),
    banner3: require('../assets/images/banner3.png'),
    banner4: require('../assets/images/banner4.png'),
    video1: require('../assets/images/video1.png'),
    video2: require('../assets/images/video2.png'),
    video3: require('../assets/images/video3.png'),
    Verifed: require('../assets/images/Verifed.png'),
    dropaerrow: require('../assets/images/dropaerrow.png'),
    alcohol: require('../assets/images/alcohol.png'),
    Zodiac: require('../assets/images/Zodiac.png'),
    hobbies: require('../assets/images/hobbies.png'),
    pets: require('../assets/images/pets.png'),
    smoking: require('../assets/images/smoking.png'),
    addifocross: require('../assets/images/addifocross.png'),
    proimage: require('../assets/images/proimage.png'),
    locationicon: require('../assets/images/locationicon.png'),
    smallproimg: require('../assets/images/smallproimg.png'),
    bghome: require('../assets/images/bghome.png'),
    share: require('../assets/images/share.png'),
    users: require('../assets/images/users.png'),
    signup: require('../assets/images/signup.png'),
    homegif: require('../assets/images/homegif.png'),
    pinkloc: require('../assets/images/pinkloc.png'),
    fullscreen: require('../assets/images/fullscreen.png'),
    sayhello: require('../assets/images/sayhello.png'),

    fullscreen1: require('../assets/images/fullscreen1.png'),
    fullscreen2: require('../assets/images/fullscreen2.png'),
    fullprofile: require('../assets/images/fullprofile.png'),
    sceneer: require('../assets/images/sceneer.png'),
    chat: require('../assets/images/chat.png'),
    Qrcode: require('../assets/images/Qrcode.png'), 
    Congratulations: require('../assets/images/Congratulations.png'),
    sayhellowithhand: require('../assets/images/sayhellowithhand.png'),
    chatmic: require('../assets/images/chatmic.png'),
    chatsgallery: require('../assets/images/chatsgallery.png'),
    chatsend: require('../assets/images/chatsend.png'),
    openfilter: require('../assets/images/openfilter.png'),
    makevideo: require('../assets/images/makevideo.png'),
    English: require('../assets/images/English.png'),
    China: require('../assets/images/China.png'),
    Spanish: require('../assets/images/Spanish.png'),
    France: require('../assets/images/France.png'),
    Germany: require('../assets/images/Germany.png'),
    Italian: require('../assets/images/Italian.png'),
    Portuguese: require('../assets/images/Portuguese.png'),
    searchicon: require('../assets/images/searchicon.png'),
    imageCropback: require('../assets/images/imageCropback.png'),
    Gallery: require('../assets/images/Gallery.png'),
    camera: require('../assets/images/camera.png'),
    pointhistory: require('../assets/images/getPoint_history.png'),
    mapflage:require('../assets/images/mapflage.png'),
    Left_arrow:require('../assets/images/Left_arrow.png'),
    Blue_box:require('../assets/images/Blue_box.png'),
    Blue_box_two:require('../assets/images/Blue_box_two.png'),
    youtube:require('../assets/images/youtube.png'),
    Russia:require('../assets/images/Russia.png'),
    user_chat:require('../assets/images/user_chat.png'),
    Showprofile_user:require('../assets/images/Showprofile_user.png')
}