export default {
    Home:"Home",
    Otp:  "Otp",
    Splash:  "Splash",
    Login:  "Login",
    Addinformation:"Addinformation",
    Addvideo:"Addvideo",
    Chat:"Chat",
    ChooseLanguage:"ChooseLanguage",
    Congrachulation:"Congrachulation",
    Connectnotification:"Connectnotification",
    Faceliveness:"Faceliveness",
    Getpointinfo:  "Getpointinfo", 
    Information:  "Information", 
    Lifestyle:  "Lifestyle", 
    Map:  "Map", 
    Matchnotification:  "Matchnotification", 
    Memberconnection:  "Memberconnection", 
    Mysearch:  "Mysearch", 
    Openchat:  "Openchat",
    Persionalinfo:  "Persionalinfo",
    Professionaldetails:  "Professionaldetails",
    Promotinoalbanner:  "Promotinoalbanner",
    Qrcode:  "Qrcode",
    Showprofile:  "Showprofile",
    Subscription:  "Subscription", 
    Takeselfi:  "Takeselfi",
    Payment:  "Payment",
    Verified:  "Verified",
    Wenttodislikes:  "Wenttodislikes",
    Wenttolikes:  "Wenttolikes",
    Successfulpayment:"Successfulpayment",
    Getpointhiostry:"Getpointhiostry",
    Chatlist:"Chatlist",
    Uploaddocimg:"Uploaddocimg",
    Uploadfacelicence:"Uploadfacelicence",
    OutofRange:"OutofRange",
    ScanQr:"ScanQr",
    TermsPrivacy:"TermsPrivacy",
    Couplelist:"Couplelist",
    TempChat:"TempChat"
}